### ISSUE TITLE
Enable Git Releases only for the Master Branch

### ISSUE THREAD

**Issue by hjchanna** [jenananthan/wso2-projects-creator#5]
As I noticed in the project, It pushes releases to the GitHub for each and every build. We should stop that and make sure releases are pushed by ci build of the master branch.

**Comment by jenananthan** [comment]
Fixed with https://github.com/jenananthan/wso2-projects-creator/commit/239baa818bf64995dda68feb4641fa78bb0cff9e

Already created branches should have this change to stop getting build
